### ISSUE TITLE
[W][component:214]: Component display took a long time for an operation (0.10 s).

### ISSUE THREAD

**Issue by jojkopeter** [justr0st/esphome-RGB-LED-pixel-clock#3]
Hello,
I tried to install the code. Unfortunately I keep getting errors:
[W][component:214]: Component display took a long time for an operation (0.10 s).
[W][component:215]: Component display took a long time for an operation (0.10 s).

Can you help me?
Please

**Comment by justr0st** [comment]
There is already the issue for ESPHome with this regard: [#4717](https://github.com/esphome/esphome/issues/9517)
Seems to be happening with newer versions for some reason. Should be just a message, that you can ignore in log, as the logging became more verbose since some version of ESPHome.
It looks like, you can disable warning messages by setting log level to ERROR:
```YAML
logger:
  logs:
    component: ERROR
```

**Comment by justr0st** [comment]
Closed as the issue seems to be no longer relevant.
